Repository LifeInvaders/game, pull requests merged in 2021-02, with the labels that each got.

#25 Added house on the hill
  .idea/.idea.game.dir/.idea/contentModel.xml
  .idea/.idea.game.dir/.idea/modules.xml
  .idea/.idea.game.dir/.idea/workspace.xml
  Assets/Objects/Map Objects/Cuba_Plain_White.prefab
  Assets/Photon/PhotonUtilities/PackObject/CodeGen/Editor/Resources/TypeCatalogue.asset
  Assets/Scenes/Map.unity
Labels: Map

#34 Radar + Gamepad Controler + Death Shader + Demo Map Soutenance
  .idea/.idea.game/.idea/contentModel.xml
  .idea/.idea.game/.idea/indexLayout.xml
  .idea/.idea.game/.idea/riderModule.iml
  .idea/.idea.game/.idea/workspace.xml
  Assets/Animations/Fx.meta
  Assets/Controler.cs
  Assets/Controler.inputactions
  Assets/InputSystem.inputsettings.asset
  Assets/Objects/Dynamic Objects/FX.meta
  Assets/Objects/Dynamic Objects/Lights/Torch.prefab
  Assets/Objects/Dynamic Objects/football/ball.prefab
  Assets/Objects/NPC/NPC.controller
  Assets/Photon/PhotonUtilities/PackObject/CodeGen/Editor/Resources/TypeCatalogue.asset
  Assets/Scenes/soutenance.meta
  Assets/Scenes/soutenance.unity
  Assets/Scenes/soutenance.unity.meta
  Assets/Scenes/soutenance/NavMesh.asset
  Assets/Scenes/soutenance/NavMesh.asset.meta
  Assets/Scenes/test2.meta
  Assets/Scenes/test2.unity
  Assets/Scenes/test3.unity
  Assets/Scripts/Photon/Resources/Player.prefab
  Assets/Scripts/RadarSystem/Radar.cs
  Assets/Scripts/TargetSystem/CastTarget.cs
  Assets/Scripts/TargetSystem/KillTarget.cs
  Assets/Scripts/TargetSystem/SelectedTarget.cs
  Assets/Shaders/Radar.shadergraph
  Assets/Shaders/Radar.shadergraph.meta
  Assets/Shaders/disolve.shadergraph
  Assets/Shaders/disolve.shadergraph.meta
  Assets/Shaders/dissolved.mat
  Assets/Shaders/dissolved.mat.meta
  Assets/Shaders/radar.mat
  Assets/Shaders/radar.mat.meta
  Assets/Shaders/radarShader.shadergraph
  Assets/Shaders/radarShader.shadergraph.meta
  Assets/demoEvent.cs
  Assets/demoEvent.cs.meta
  ProjectSettings/GraphicsSettings.asset
Labels: Gamecore, enhancement

#38 Update Demo Map
  .idea/.idea.game/.idea/contentModel.xml
  Assets/Controler.cs
  Assets/Controler.inputactions
  Assets/Photon/PhotonUtilities/PackObject/CodeGen/Editor/Resources/TypeCatalogue.asset
  Assets/ResetDemoScene.cs
  Assets/ResetDemoScene.cs.meta
  Assets/Scenes/soutenance.unity
  Assets/Scripts/Photon/Resources/Player.prefab
  Assets/Shaders/disolve.shadergraph
  Assets/Shaders/dissolved.mat
  Assets/demoEvent.cs
  ProjectSettings/EditorBuildSettings.asset
  ProjectSettings/ProjectSettings.asset
Labels: enhancement

#41 Update KillSystem
  Assets/Scripts/TargetSystem/KillTarget.cs
Labels: IA, bug, enhancement
